package programa;

public class ControleUsuariosTemp {
	
	//VOLTAR TODA A LÓGICA DO CONTROLE USUARIOS PRAK E USAR CONTROLE USUARIOS COM OS MÉTODOS COMUNS A EMPRESA E CLIENTE
	
	//SE EU FIZER ISSO TEREI UMA CLASSE CONTROLE SEM REPOSITÓRIO, POIS SE TORNA AMBIGUO

	// SE NAO ROLAR VOU COLOCAR UM BOTÃO NA TELA DE LOGIN PARA DECIDIR ENTRE USER E EMPRESA
}
